"""create scheduling tables

Revision ID: b99f405ccfb2
Revises: 202607150702
Create Date: 2026-07-15 17:06:33.516135
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b99f405ccfb2"
down_revision: str | Sequence[str] | None = "202607150702"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_pool_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phase_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_point_id", sa.Uuid(), nullable=False),
        sa.Column("task_template_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=320), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("est_minutes", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("est_minutes > 0", name="ck_task_pool_items_est_minutes"),
        sa.ForeignKeyConstraint(
            ["knowledge_point_id"], ["knowledge_points.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["material_id"], ["materials.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["phase_id"], ["plan_phases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_template_id"], ["task_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "phase_id", "task_template_id", "knowledge_point_id", name="uq_task_pool_items_source"
        ),
    )
    op.create_index(
        op.f("ix_task_pool_items_knowledge_point_id"),
        "task_pool_items",
        ["knowledge_point_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_pool_items_material_id"), "task_pool_items", ["material_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_pool_items_phase_id"), "task_pool_items", ["phase_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_pool_items_subject_id"), "task_pool_items", ["subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_pool_items_task_template_id"),
        "task_pool_items",
        ["task_template_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pool_item_id", sa.Uuid(), nullable=True),
        sa.Column("phase_id", sa.Uuid(), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("knowledge_point_id", sa.Uuid(), nullable=True),
        sa.Column("material_id", sa.Uuid(), nullable=True),
        sa.Column("phase_name", sa.String(length=80), nullable=False),
        sa.Column("subject_name", sa.String(length=80), nullable=False),
        sa.Column("knowledge_point_name", sa.Text(), nullable=False),
        sa.Column("material_name", sa.String(length=120), nullable=True),
        sa.Column("title", sa.String(length=320), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("planned_date", sa.Date(), nullable=False),
        sa.Column("est_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("actual_minutes", sa.Integer(), nullable=True),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("carry_count", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('planned', 'completed', 'skipped')", name="ck_scheduled_tasks_status"
        ),
        sa.CheckConstraint(
            "actual_minutes IS NULL OR actual_minutes >= 0",
            name="ck_scheduled_tasks_actual_minutes",
        ),
        sa.CheckConstraint("carry_count >= 0", name="ck_scheduled_tasks_carry_count"),
        sa.CheckConstraint("est_minutes > 0", name="ck_scheduled_tasks_est_minutes"),
        sa.ForeignKeyConstraint(
            ["knowledge_point_id"], ["knowledge_points.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["material_id"], ["materials.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["phase_id"], ["plan_phases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["pool_item_id"], ["task_pool_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pool_item_id", name="uq_scheduled_tasks_pool_item"),
    )
    op.create_index(
        op.f("ix_scheduled_tasks_knowledge_point_id"),
        "scheduled_tasks",
        ["knowledge_point_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_tasks_material_id"), "scheduled_tasks", ["material_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_tasks_phase_id"), "scheduled_tasks", ["phase_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_tasks_planned_date"), "scheduled_tasks", ["planned_date"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_tasks_pool_item_id"), "scheduled_tasks", ["pool_item_id"], unique=False
    )
    op.create_index(op.f("ix_scheduled_tasks_status"), "scheduled_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_scheduled_tasks_subject_id"), "scheduled_tasks", ["subject_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_tasks_subject_id"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_status"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_pool_item_id"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_planned_date"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_phase_id"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_material_id"), table_name="scheduled_tasks")
    op.drop_index(op.f("ix_scheduled_tasks_knowledge_point_id"), table_name="scheduled_tasks")
    op.drop_table("scheduled_tasks")
    op.drop_index(op.f("ix_task_pool_items_task_template_id"), table_name="task_pool_items")
    op.drop_index(op.f("ix_task_pool_items_subject_id"), table_name="task_pool_items")
    op.drop_index(op.f("ix_task_pool_items_phase_id"), table_name="task_pool_items")
    op.drop_index(op.f("ix_task_pool_items_material_id"), table_name="task_pool_items")
    op.drop_index(op.f("ix_task_pool_items_knowledge_point_id"), table_name="task_pool_items")
    op.drop_table("task_pool_items")
    # ### end Alembic commands ###
